# Generated by Django 4.2.7 on 2023-11-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0002_auto_20200524_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='username',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
