# Generated by Django 4.2.7 on 2023-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0002_auto_20200524_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='organ',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
