# Generated by Django 4.2 on 2023-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMON_APP', '0003_remove_receptionist_username_appointment_organ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='machine',
            field=models.TextField(default='', max_length=50, null=True),
        ),
    ]
