# Generated by Django 4.2.7 on 2023-11-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENT', '0001_initial'),
        ('COMMON_APP', '0004_appointment_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=4)),
                ('taken_beds', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='wheelchair',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PATIENT.patient')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COMMON_APP.rooms')),
            ],
        ),
    ]
